alias g='git'
compdef g=git
alias gst='git status'
compdef _git gst=git-status
alias gd='git diff'
compdef _git gd=git-diff
alias gdc='git diff --cached'
compdef _git gdc=git-diff
alias gds='git diff --staged'
compdef _git gds=git-diff
alias gpl='git pull'
compdef _git gpl=git-fetch
alias gpr='git pull --rebase'
compdef _git gpr=git-fetch
alias gp='git push'
compdef _git gp=git-push
alias gc='git commit -v'
compdef _git gc=git-commit
alias gc!='git commit -v --amend'
compdef _git gc!=git-commit
alias gca='git commit -v -a'
compdef _git gc=git-commit
alias gco='git checkout'
compdef _git gco=git-checkout
alias gcm='git checkout master'
compdef _git gcm=git-checkout
alias glg='git log --stat --max-count=10'
compdef _git glg=git-log
alias ga='git add'
compdef _git ga=git-add
